### ISSUE TITLE
Importing file with extern attributes causes "External function cannot have a body" error

### ISSUE THREAD

**Issue by judah-caruso** [MrSmith33/vox#16]
I may be misunderstanding how `@extern` can be used, but the following program results in an error.

```d
// main.vox
#version(windows) {
    import win;
}

void main() {
    #version(windows) ExitProcess(0);
}
```

```d
// win.vox
@extern(module, "kernel32")
void ExitProcess(u32 uExitCode);

@extern(module, "kernel32")
void* GetStdHandle(u32 nStdHandle);

// ...
```

Command: `vox main.vox win.vox [location of kernel32.dll]`

Output:
```
win.vox:1:1: Error: External function cannot have a body
```

Copying and pasting the contents of `win.vox` into `main.vox` fixes this.

**Comment by MrSmith33** [comment]
Hello. Thanks for report!

`@extern(module, "kernel32")` feature is still not implemented, but the `External function cannot have a body` error here is a bug. I will fix this soon, but for the time being omit the `@extern` attribute and will work.
