### ISSUE TITLE
ICE: getAst(VariableDeclNode) got cast(AstType)255

### ISSUE THREAD

**Issue by rempas** [MrSmith33/vox#44]
**Expected behavior**
Similar to #43 but now the a templated parameter is used instead.

**Describe the bug**
The error message is now:

```
vox.context:574: ICE: getAst(VariableDeclNode) got cast(AstType)255
Stack:
> test.vox:14:9: node.1164 type_check expr_call printa
  test.vox:13:13: node.1204 type_check stmt_block stmt_block
  test.vox:13:6: node.1073 type_check decl_function main
  test.vox:1:1: node.485 type_check decl_module test
vox.context.CompilationException@vox.context(574)
----------------
??:? [0x55835b29249c]
??:? [0x55835b273f6d]
??:? [0x55835b0c21bd]
??:? [0x55835b0c1d69]
??:? [0x55835b17da25]
??:? [0x55835b178736]
??:? [0x55835b17865a]
??:? [0x55835b178b7f]
??:? [0x55835b19c5df]
??:? [0x55835b24628f]
??:? [0x55835b24d508]
??:? [0x55835b273bfe]
??:? [0x55835b273a80]
??:? [0x55835b2738dd]
??:? [0x7fe1a7f9c30f]
??:? __libc_start_main [0x7fe1a7f9c3c0]
??:? [0x55835b1bfe2d]
```

**To Reproduce**
The function signature is now:

```
void printa[Args](Args... data) {
  sys_write(1, data[1].ptr, data[1].length);
  sys_write(1, data[2].ptr, data[2].length);
  sys_write(1, data[3].ptr, data[3].length);
}
```

**Additional context**
 - OS: Linux
 - Hash: 2278275397269d6c5a6f3943dfe488668dd015a6

**Comment by MrSmith33** [comment]
How did you instantiate `printa`?

**Comment by rempas** [comment]
Yes! For some reason, I had the feeling that you didn't had to create an instance to get the error but you do! Hence the following code can be used as a reference:

```
@extern(syscall, 60)
void exit(i32 exit_code);

void printa[Args](Args... data) {
  sys_write(1, data[1].ptr, data[1].length);
  sys_write(1, data[2].ptr, data[2].length);
  sys_write(1, data[3].ptr, data[3].length);
}

void main () {
  printa("Hello", ", ", "world!\n");
  exit(0);
}
```

**Comment by MrSmith33** [comment]
The correct syntax would be
```D
void printa[Args...](Args... data) {
  sys_write(1, data[1].ptr, data[1].length);
  sys_write(1, data[2].ptr, data[2].length);
  sys_write(1, data[3].ptr, data[3].length);
}
```
but I will fix the crash to give proper error message

**Comment by rempas** [comment]
Wait wait wait! I'm veeery confused here! Is the syntax you mentioned supposed to work? Is this what you mean be saying with the phrase "correct syntax"? I used the following code:

```
@extern(syscall, 60)
void exit(i32 exit_code);

@extern(syscall, 1)
void sys_write(u32 fd, void* ptr, u64 length);

void printa[Args...](Args... data) {
  sys_write(1, data[1].ptr, data[1].length);
  sys_write(1, data[2].ptr, data[2].length);
  sys_write(1, data[3].ptr, data[3].length);
}

void main () {
  printa("Hello", ", ", "world!\n");
  exit(0);
}
```
And it tries to compile for about 9 seconds and then I get the infamous segmentation fault (core dumped). Was this supposed to happen?

Also keep in mind that `[Args...]` and `[Args]` mean two different things. As the first one allows every instance of "Args" to be any type and the second forces every instance to be the same type so both of them should be supported right?

**Comment by MrSmith33** [comment]
yes, template argument `Args...` matches 0 or more types and is supposed to be matched in runtime arguments with the same `Args... args`. I may change this syntax in the future though. Singular `Args` is a single type.
The hang is a bug, because compiler code atm missed a check for using runtime `Args...` without matching `Args...` template arg.

**Comment by rempas** [comment]
It still gives a segmentation fault when I'm trying to compile tho

**Comment by rempas** [comment]
I STARTING INDEXING WITH 1!? OMG I'm blind!!!!! Thankfully, I found a bug this way.

Yeah, starting with 0 makes it work and now! The out of index message is awesome! Simple and clean!

Thanks for allowing to index the variadic array like that! That's not only simple compare to the dirty and ugly [solution](https://forum.dlang.org/post/hoeukipesnuamnobqewa@forum.dlang.org) we need to use in D but it will also not introduce any runtime cost.

Now, I only wait for been able to link with ".so" so I can convert my language's front end code from D to Vox.

However, I don't need linking with ".so" libraries to create a system library in Vox. I'll a little bit sick right now and I'm mostly in the bed so I will start working on it when I feel better. Thanks a lot for the quick replies and fixes!

**Comment by MrSmith33** [comment]
In Vox it works exactly like in D btw

**Comment by rempas** [comment]
This works in D? Are you sure about that? I converted the code and I'm trying to compile and I get the following error message (using ldc2):

```
test.d(10): Error: template `test.printa` cannot deduce function from argument types `!()(string, string, string)`
test.d(3):        Candidate is: `printa(Args...)(Args data...)`
```

The code is:

```d
import core.sys.linux.unistd;

void printa(Args...)(Args data...) {
  write(1, data[0].ptr, data[0].length);
  write(1, data[1].ptr, data[1].length);
  write(1, data[2].ptr, data[2].length);
}

extern (C) void main() {
  printa("Hello", ", ", "world!\n");
}
```

**Comment by MrSmith33** [comment]
In D you don't need to use `...` on runtime argument, so the code is:
```D
import core.sys.linux.unistd;

void printa(Args...)(Args data) {
  write(1, data[0].ptr, data[0].length);
  write(1, data[1].ptr, data[1].length);
  write(1, data[2].ptr, data[2].length);
}

extern (C) void main() {
  printa("Hello", ", ", "world!\n");
}
```

**Comment by MrSmith33** [comment]
https://dlang.org/spec/template.html#variadic-templates

**Comment by rempas** [comment]
That's cool! Indexing doesn't work as clean an nice as in Vox tho. Also, it requires Phobos to be linked which is a big no no!

**Comment by MrSmith33** [comment]
> Indexing doesn't work as clean an nice as in Vox tho

Not sure what you mean here without an example
>Also, it requires Phobos to be linked which is a big no no!

same here

**Comment by MrSmith33** [comment]
Actually you can define it yourself in [one line](https://dlang.org/library/std/meta/alias_seq.html):
```D
alias AliasSeq(TList...) = TList;
```
and in Vox it barely exists yet.

**Comment by rempas** [comment]
Nice! Still it needs Phobos!
