### ISSUE TITLE
I'm getting the "illegal hardware instruction" error when I execute the "vox" executable

### ISSUE THREAD

**Issue by rempas** [MrSmith33/vox#46]
**Expected behavior**
To not get this error.

**Describe the bug**
When I run Vox, I'm getting the error in the title.

**To Reproduce**
Just trying to execute the "vox" executable results in an "illegal hardware instruction" error to be printed. I also tried to use the debug version of the built-in CI builds but it didn't showed anything more. It seems that the only thing that seems to output something more is when I run it with an unrecognized option. In that case, I also get the message that the option is unrecognized and then again, I get the "illegal hardware instruction" error.

**Additional context**
 - OS: Linux
 - f8849389256e58223b4c2afb10db9e1db8fea58d

**Comment by MrSmith33** [comment]
Can you try these 2 versions?
* https://github.com/MrSmith33/vox/actions/runs/2148059127
* https://github.com/MrSmith33/vox/actions/runs/2149431175

Also, what is your CPU?

**Comment by rempas** [comment]
> Also, what is your CPU?

Ryzen 5 2400G
