### ISSUE TITLE
Build fails on Ubuntu 21.04

### ISSUE THREAD

**Issue by nordlow** [MrSmith33/vox#6]
Building master on Ubuntu 21.04 fails as

```
~/.local/ldc2-1.26.0-beta1-linux-x86_64/bin/../import/std/bitmanip.d(313): Error: static assert:  "Wrong size of bitfield: 12"
be/debug_info/pdb/symbol.d(407):        instantiated from here: `bitfields!(CV_SourceLanguage, "sourceLanguage", 8, bool, "pcode", 1, ubyte, "floatprec", 2, ubyte, "floatpkg", 2, ubyte, "ambdata", 3, ubyte, "ambcode", 3, bool, "mode32", 1, ubyte, "pad", 12)`
```

**Comment by MrSmith33** [comment]
Looks like `bitfields` started to check the fields size against type in the newest phobos. So `12` bits is too much for `ubyte`, but it doesn't say it in a sane way. And doesn't mention which field is wrong and why. The fix is to replace `ubyte` with `ushort`
